model:
    # relative to mmseg_code_dir
    config: configs/fastscnn/fast_scnn_lr0.12_8x4_160k_cityscapes.py
data:
    root_dir: /data1/wangjiaxin/cvdatasets/cityscapes
    class_names: ['road', 'sidewalk', 'building', 'wall', 'fence', 'pole',
               'traffic light', 'traffic sign', 'vegetation', 'terrain', 'sky',
               'person', 'rider', 'car', 'truck', 'bus', 'train', 'motorcycle',
               'bicycle']
train:
    # support mmsegmentation 0.30.0
    gpu: 4
    mmseg_code_dir: '/data1/wangjiaxin/gnu/mmsegmentation'
mining:
    mining_algorithm: rsal
    fp16: True
    samples_per_gpu: 2
    topk_superpixel_score: 3
    aug_test: False
    # the omega output config file, need to add index_file and config_file
    omega_config_file: ./omega_config.yaml
    # mmsegmentation config file
    config_file: xxx.py
    checkpoint: xxx.pt
    # rsal hyper-parameters
    uncertainty_method: BvSB
    superpixel_algorithm: slico # seeds, slic, slico, mslic
    class_balance: True
    max_superpixel_per_image: 1024
    max_kept_mining_image: 5000
    # ripu hyper-parameters
    ripu_region_radius: 1
output:
    root_dir: /data1/wangjiaxin/tmp
